# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS_DEMO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 5.5'
  # Pods for IOS_DEMO


  target 'IOS_DEMOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOS_DEMOUITests' do
    # Pods for testing
  end

end

